# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
# baseURL = "https://csiebler.github.io"
baseURL = "https://clemenssiebler.com"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    ID = "G-HB3D5YJ128"
